before_script: 
    - python3 ./gitlab-ci/prepare_to_run_tests.py ~/oge_build_root/
    - vncserver :42 -geometry 1920x1080 -localhost -nolisten tcp
    - DISPLAY=:42.0
    - export DISPLAY
      
test:
    script: 
      - cd ~/oge_build_root/osate2-core/osate.releng/
      - mvn -P local -fae clean integration-test
      
after_script:
      - vncserver -kill :42